import { v4 as uuid } from 'uuid';
import { IFile } from "../interfaces";

export const fileTree: IFile = {
  id: uuid(),
  name: "VS Code Clone",
  isFolder: true,
  children: [
    {
      id: uuid(),
      name: "node_modules",
      isFolder: true,
      children: [
        {
          id: uuid(),
          name: ".vite",
          isFolder: true, 
          children: [
            {
              id: uuid(), name: "react.js", isFolder: false,content: `interface IProps {

}

const Button = ({}: IProps) => {
  return (
    <button>Click me!</button>
  )
}

export default Button`,
            }
          ]
        }
      ]
    },
    {
      id: uuid(),
      name: "public",
      isFolder: true,
      children: [
        {
          id: uuid(),
          name: "vite.svg",
          isFolder: false,
          content: `<svg xmlns="http://www.w3.org/2000/svg"></svg>`,
        },
      ],
    },
    {
      id: uuid(),
      name: "src",
      isFolder: true,
      children:[
        {
          id: uuid(),
          name: "components",
          isFolder: true,
          children: [
            {
              id: uuid(),
              name: "Button.tsx",
              isFolder: false,
              content: "Button Component Content"
            }
          ]
        },
        {
          id: uuid(),
          name: "app.tsx",
          isFolder: false
        },
        {
          id: uuid(),
          name: "index.css",
          isFolder: false
        },
        {
          id: uuid(),
          name: "main.tsx",
          isFolder: false,
          content:
          `import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import { Provider } from 'react-redux'
import { store } from './app/store.ts'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <Provider store={store}>
    <App />
  </Provider>
)`
        },
      ]
    },
    {
      id: uuid(),
      name: ".gitignore",
      isFolder: false,
      content: `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local
      `
    },
    {
      id: uuid(),
      name: "index.html",
      isFolder: false,
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
    },
    {
      id: uuid(),
      name: "package-lock.json",
      isFolder: false
    },
    {
      id: uuid(),
      name: "package.json",
      isFolder: false
    },
    {
      id: uuid(),
      name: "README.md",
      isFolder: false
    },
    {
      id: uuid(),
      name: "tailwind.config",
      isFolder: false,
      content:`/** @type {import('tailwindcss').Config} */
    export default {
      content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
      theme: {
      extend: {},
    },
    plugins: [],
  };
`
    },
    {
      id: uuid(),
      name: "vite.config.ts",
      isFolder: false,
      content:`import { defineConfig } from 'vite'
      import react from '@vitejs/plugin-react'
      // https://vitejs.dev/config/
      export default defineConfig({
        plugins: [react()],
      })`
    },
    {
      id: uuid(),
      name: "yarn.lock",
      isFolder: false,
      content:`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
"@aashutoshrathi/word-wrap@^1.2.3":
version "1.2.6"
resolved "https://registry.npmjs.org/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz"
integrity sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==
      
      "@alloc/quick-lru@^5.2.0":
version "5.2.0"
resolved "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz"
integrity sha512-UrcABB+4bUrFABwbluTIBErXwvbsU/V7TZWfmbgJfbkwiBuziS9gxdODUyuiecfdGQ85jglMW6juS3+z5TsKLw==
      "@ampproject/remapping@^2.2.0":
version "2.2.1"
resolved "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.1.tgz"
integrity sha512-lFMjJTrFL3j7L9yBxwYfCq2k6qqwHyzuUl/XBnif78PWTJYyL/dfowQHWE3sp6U6ZzqWiiIZnpTMO96zhkjwtg==
dependencies:
  "@jridgewell/gen-mapping" "^0.3.0"
  "@jridgewell/trace-mapping" "^0.3.9"
      `
    }
  ]
}